### ISSUE TITLE
Color detection errors

### ISSUE THREAD

**Issue by maejoh** [wyattschwanbeck/Game-Automation-With-Python-Computer-Vision#2]
![image](https://user-images.githubusercontent.com/22644177/168487298-53073821-0b0a-47e1-bc12-52b4733a921f.png)

Colors often (but not always) "bleed" into the squares one below and/or one to the right of themselves

**Comment by maejoh** [comment]
Wraparound bleed

![image](https://user-images.githubusercontent.com/22644177/168494033-189e065a-d310-4016-bc77-3fe3e0bc91d4.png)

Another step, bleed changes

![image](https://user-images.githubusercontent.com/22644177/168494076-d838a226-761b-4da7-a9fe-be73226f85b8.png)

Bleed overlap

![image](https://user-images.githubusercontent.com/22644177/168494217-c7124448-e867-4823-8c94-3e96b1a1e2ed.png)

Another step and the bottom orange is back to bleeding

![image](https://user-images.githubusercontent.com/22644177/168494256-8601b107-1d02-434d-8578-c4c57be06e82.png)

This ones interesting

![image](https://user-images.githubusercontent.com/22644177/168494285-831f0edf-87c7-46c3-9f08-3d8781ba4f19.png)

**Comment by wyattbradley34** [comment]
Please test the latest commit in the color-detection-issue branch and let me know if the issue persists. This required an entire rework of the detection procedure leveraging a threshold parameter for amount of pixels matching colors and verifying at least 3 sides contain colors matched.
